//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingProjectDataLayer.DataLayer.Entities.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionLog
    {
        public int ExceptionLogId { get; set; }
        public string SessionId { get; set; }
        public string LoggedInUser { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string InnerException { get; set; }
        public System.DateTime OccuredOn { get; set; }
        public string MethodName { get; set; }
        public string Source { get; set; }
        public string Message { get; set; }
        public int LineNumber { get; set; }
    }
}
