//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingProjectDataLayer.DataLayer.Entities.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportsType
    {
        public int ReportTypeID { get; set; }
        public string ReportName { get; set; }
        public int ReportDesignType { get; set; }
        public string ReportHeader { get; set; }
        public string ReportTableView { get; set; }
        public string ReportDetailView { get; set; }
        public string ReportTittleName { get; set; }
    }
}
