//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingProjectDataLayer.DataLayer.Entities.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public int UserLogId { get; set; }
        public int UserId { get; set; }
        public string SessionId { get; set; }
        public string ConnectionId { get; set; }
        public bool OnlineStatus { get; set; }
        public System.DateTime LoggedInTime { get; set; }
        public Nullable<System.DateTime> LoggedOutTime { get; set; }
        public string SystemInfo { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> LastAcessedOn { get; set; }
        public bool IsOfflineByAdmin { get; set; }
    
        public virtual User User { get; set; }
    }
}
